### ISSUE TITLE
Debouncing the municipality search query

### ISSUE THREAD

**Issue by ratron** [cividi/spatial-data-package-platform#83]
@apttx recommend [debouncing](https://www.npmjs.com/package/debounce) the search query.

vue apollo has [its own](https://apollo.vuejs.org/api/smart-query.html) debouncing functionality.

_Originally posted by @apttx in https://github.com/cividi/spatial-data-package-platform/issues/76#issuecomment-796854850_

@ratron thinks it's a great idea, but not super urgent. but since apollo already has an option, it should be rather quick to implement

**Comment by ratron** [comment]
@n0rdlicht do you want to add that to the 0.7.1 or 0.8 Milestone?

**Comment by n0rdlicht** [comment]
> @n0rdlicht do you want to add that to the 0.7.1 or 0.8 Milestone?

Let's include it in 0.7.1, I'll add it.

**Comment by glaand** [comment]
Unfortunately apollo doesn't provide a global way for debouncing queries, which makes sense, since we don't want to debounce all requests on the graphql server.

For now, i've just debounced the municipality query.

Take a look, if it's fine, let's merge it 🦾 
https://github.com/cividi/spatial-data-package-platform/commit/984a58dfce5e456aed6f9b174e73ba03a729b7a4
